# Generated by Django 5.0.4 on 2024-04-10 18:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_entrepreneur', models.CharField(max_length=50, verbose_name='имя предпринимателя')),
                ('email_entrepreneur', models.EmailField(max_length=50, verbose_name='почта предпринимателя')),
                ('country_entrepreneur', models.CharField(max_length=50, verbose_name='страна предпринимателя')),
                ('city_entrepreneur', models.CharField(max_length=50, verbose_name='город предпринимателя')),
                ('street_entrepreneur', models.CharField(max_length=50, verbose_name='улица предпринимателя')),
                ('house_number_entrepreneur', models.IntegerField(default=0, verbose_name='номер дома предпринимателя')),
                ('name_product', models.CharField(max_length=50, verbose_name='название продукта')),
                ('model_product', models.CharField(max_length=50, verbose_name='модель продукта')),
                ('date_product_release', models.DateField(default=datetime.date.today, verbose_name='дата выхода продукта на рынок')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='задолженность')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retail', verbose_name='розничная сеть')),
            ],
            options={
                'verbose_name': 'предприниматель',
                'verbose_name_plural': 'предприниматели',
            },
        ),
    ]
