# Generated by Django 5.0.4 on 2024-04-10 18:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_retail', models.CharField(max_length=50, verbose_name='название розничной сети')),
                ('email_retail', models.EmailField(max_length=50, verbose_name='почта розничной сети')),
                ('country_retail', models.CharField(max_length=50, verbose_name='страна розничной сети')),
                ('city_retail', models.CharField(max_length=50, verbose_name='город розничной сети')),
                ('street_retail', models.CharField(max_length=50, verbose_name='улица розничной сети')),
                ('house_number_retail', models.IntegerField(default=0, verbose_name='номер дома розничной сети')),
                ('name_product', models.CharField(max_length=50, verbose_name='название продукта')),
                ('model_product', models.CharField(max_length=50, verbose_name='модель продукта')),
                ('date_product_release', models.DateField(default=datetime.date.today, verbose_name='дата выхода продукта на рынок')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='задолженность')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='завод')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
    ]
